version: "3.8"

services:
  postgres:
    container_name: postgres
    image: "pg_hashids"
    build:
      context: pg_hashids
      dockerfile: Dockerfile

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - "./db-data:/data/postgres"
    ports:
      - "5432:5432"
    networks:
      - "contest_buddy_network"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DISABLE_POSTFIX: "True"

    volumes:
      - "./pgadmin-data:/root/.pgadmin"
      - "./pgadmin_servers.json:/pgadmin4/servers.json"
      - "./pgpass.conf:/pgpass.conf"

    ports:
      - "${PGADMIN_PORT:-8889}:80"
    networks:
      - "contest_buddy_network"
    restart: unless-stopped

networks:
  contest_buddy_network:
    driver: bridge

volumes:
  db-data: {}
  pgadmin-data: {}
  pgadmin_servers.json: {}
  pgpass.conf: {}
